### ISSUE TITLE
Possible options for args in operator deployment

### ISSUE THREAD

**Issue by gmichels** [Dynatrace/helm-charts#15]
Hello,

In https://github.com/Dynatrace/helm-charts/blob/fa4baebbf8912930eadcb6d09bcde3f79ea0ca1a/dynatrace-oneagent-operator/values.yaml#L24 one can set the OneAgent arguments such as enable log access.

I am interested in setting the host group, and in the manual deployment, OneAgent has arguments in this form:

```
    - name: dynatrace-oneagent
      image: 'docker.io/dynatrace/oneagent:latest'
      args:
        - APP_LOG_CONTENT_ACCESS=1
        - HOST_GROUP=GROUP_NAME
```

What are the available options in the `args` list?

Thanks
