### ISSUE TITLE
Kubernetes automatic monitoring - cluster name?

### ISSUE THREAD

**Issue by lilley2412** [Dynatrace/helm-charts#181]
Following instructions here https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/connect-your-k8s-clusters#auto, I'm installing the chart `dynatrace-operator/chart/default` from https://github.com/Dynatrace/helm-charts.git revision `dynatrace-operator-v0.4.1`, using these helm values (the secret is created by another process):

```
      platform: kubernetes
      apiUrl: https://*******.live.dynatrace.com/api
      autoCreateSecret: false
      operator:
        image: docker.io/dynatrace/dynatrace-operator:v0.4.1
      oneAgent:
        image: *********.live.dynatrace.com/linux/oneagent:1.233.177
      activeGate:
        capabilities:
        - kubernetes-monitoring
```

I'm also adding the annotation `alpha.operator.dynatrace.com/feature-automatic-kubernetes-api-monitoring: "true"` to the dynakube CRD.

When the cluster is autoconnected, the cluster name is "dynakube":

![image](https://user-images.githubusercontent.com/450777/156247726-66fee2c8-32a3-4634-8e03-4ad2d0069f57.png)

Is there a way to provide the cluster name to the chart so it appears correctly in the dashboard?
